# Generated by Django 5.2.8 on 2025-11-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('travel', '여행'), ('cat', '고양이'), ('dog', '강아지')], default='free', max_length=10, verbose_name='카테고리'),
        ),
    ]
